### ISSUE TITLE
Logging about errors

### ISSUE THREAD

**Issue by kallsu** [hmvictor/radar-netbeans#51]
- Download Netbeans 8.1 PHP
- Install radar plugin
- Set up SonarQube server url ( 5.5 )
- Go on project, try to retrieve the list of projec to get the issues.

I patched updating the `common-logging.jar` file under `~/.netbeans/8.1/modules/ext/org.radar.radar-netbeans/commons-logging/` directory.

I add log4j 1.2.17 class files with `jar uf commons-logging.jar org/`

This is the exception:

```
java.lang.ClassNotFoundException: org.apache.log4j.Category
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:222)
Caused: java.lang.ClassNotFoundException: org.apache.log4j.Category starting from ModuleCL@38bbaebf[org.radar.radar.netbeans] with possible defining loaders [ModuleCL@2a04d9eb[org.netbeans.modules.html.validation]] and declared parents [ModuleCL@2b733e97[org.netbeans.api.templates], ModuleCL@3925dd46[org.netbeans.modules.settings], ModuleCL@1e5838e6[org.netbeans.api.annotations.common], ModuleCL@2d5e971b[org.openide.filesystems.nb], ModuleCL@74e92c00[org.netbeans.api.progress.nb], ModuleCL@5cbb9eba[org.netbeans.api.java.classpath], ModuleCL@52f584d7[org.openide.awt], ModuleCL@62494cb[org.netbeans.modules.keyring], ModuleCL@779161f3[org.openide.text], ModuleCL@59fb59b3[org.netbeans.modules.java.project], ...13 more]
    at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:224)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Caused: java.lang.NoClassDefFoundError: org/apache/log4j/Category
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
    at java.lang.Class.getConstructor0(Class.java:3075)
    at java.lang.Class.getConstructor(Class.java:1825)
    at org.apache.commons.logging.impl.LogFactoryImpl.getLogConstructor(LogFactoryImpl.java:410)
Caused: org.apache.commons.logging.LogConfigurationException: No suitable Log constructor [Ljava.lang.Class;@5e95aeea for org.apache.commons.logging.impl.Log4JLogger (Caused by java.lang.NoClassDefFoundError: org/apache/log4j/Category)
    at org.apache.commons.logging.impl.LogFactoryImpl.getLogConstructor(LogFactoryImpl.java:413)
    at org.apache.commons.logging.impl.LogFactoryImpl.newInstance(LogFactoryImpl.java:529)
Caused: org.apache.commons.logging.LogConfigurationException: org.apache.commons.logging.LogConfigurationException: No suitable Log constructor [Ljava.lang.Class;@5e95aeea for org.apache.commons.logging.impl.Log4JLogger (Caused by java.lang.NoClassDefFoundError: org/apache/log4j/Category) (Caused by org.apache.commons.logging.LogConfigurationException: No suitable Log constructor [Ljava.lang.Class;@5e95aeea for org.apache.commons.logging.impl.Log4JLogger (Caused by java.lang.NoClassDefFoundError: org/apache/log4j/Category))
    at org.apache.commons.logging.impl.LogFactoryImpl.newInstance(LogFactoryImpl.java:543)
    at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:235)
    at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:209)
    at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:351)
    at org.apache.http.impl.client.CloseableHttpClient.<init>(CloseableHttpClient.java:58)
    at org.apache.http.impl.client.AbstractHttpClient.<init>(AbstractHttpClient.java:287)
    at org.apache.http.impl.client.DefaultHttpClient.<init>(DefaultHttpClient.java:147)
    at org.sonar.wsclient.connectors.HttpClient4Connector.initClient(HttpClient4Connector.java:132)
    at org.sonar.wsclient.connectors.HttpClient4Connector.<init>(HttpClient4Connector.java:72)
    at qubexplorer.server.SonarQube.createSonar(SonarQube.java:159)
    at qubexplorer.server.SonarQube.getProjects(SonarQube.java:279)
    at qubexplorer.ui.ProjectChooser$ProjectsTask.execute(ProjectChooser.java:253)
    at qubexplorer.ui.ProjectChooser$ProjectsTask.execute(ProjectChooser.java:241)
    at qubexplorer.ui.task.TaskExecutor$TaskWorker.doInBackground(TaskExecutor.java:62)
    at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at javax.swing.SwingWorker.run(SwingWorker.java:334)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[catch] at java.lang.Thread.run(Thread.java:745)

```

**Comment by hmvictor** [comment]
Let me figure it out because that is a transitive dependency. Radar doesn't use common-logging directly.

I have to check if there is no dependency conflict.

Thank you very much.

**Comment by hmvictor** [comment]
Dependency fixed.
