### ISSUE TITLE
HTTP 404 on retrieving action plans (SonarQube 6.2)

### ISSUE THREAD

**Issue by neshanjo** [hmvictor/radar-netbeans#54]
Hi,

I get an HTTP 404 error (shown in NetBeans notifications list):

```
org.sonar.wsclient.base.HttpException: Error 404 on https://_myserver_/sonarqube/api/action_plans/search?project=_myprojectkey_
	at org.sonar.wsclient.internal.HttpRequestFactory.execute(HttpRequestFactory.java:140)
	at org.sonar.wsclient.internal.HttpRequestFactory.get(HttpRequestFactory.java:126)
	at org.sonar.wsclient.issue.internal.DefaultActionPlanClient.find(DefaultActionPlanClient.java:47)
	at qubexplorer.server.SonarQube.getActionPlans(SonarQube.java:216)
	at qubexplorer.ui.ActionPlansTask.execute(ActionPlansTask.java:23)
	at qubexplorer.ui.ActionPlansTask.execute(ActionPlansTask.java:13)
	at qubexplorer.ui.task.TaskExecutor$TaskWorker.doInBackground(TaskExecutor.java:62)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[catch] at java.lang.Thread.run(Thread.java:745)
```

NetBeans version 8.2
SonarQube version 6.2

Has the api changed with SonarQube 6?

Best regards
Johannes

**Comment by hmvictor** [comment]
Hi, @neshanjo.

What version of the plugin is installed in Netbeans?

**Comment by neshanjo** [comment]
Version 2.6 (installed via Tools->Plugins)

**Comment by hmvictor** [comment]
Could you update or install to Radar 2.7? It has support for SonarQube 6.2.
