### ISSUE TITLE
java.lang.IllegalArgumentException: No enum constant qubexplorer.runner.SonarRunnerProccess.AnalysisMode.ISSUES

### ISSUE THREAD

**Issue by oers** [hmvictor/radar-netbeans#57]
With Netbeans 8.2 and sonarqube 6.3
```
java.lang.IllegalArgumentException: No enum constant qubexplorer.runner.SonarRunnerProccess.AnalysisMode.ISSUES
	at java.lang.Enum.valueOf(Enum.java:238)
	at qubexplorer.runner.SonarRunnerProccess$AnalysisMode.valueOf(SonarRunnerProccess.java:37)
	at qubexplorer.ui.summary.SonarRunnerTask.execute(SonarRunnerTask.java:97)
	at qubexplorer.ui.summary.SonarRunnerTask.execute(SonarRunnerTask.java:37)
	at qubexplorer.ui.task.TaskExecutor$TaskWorker.doInBackground(TaskExecutor.java:71)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[catch] at java.lang.Thread.run(Thread.java:745)
```

**Comment by hmvictor** [comment]
The quick fix is to change the analysis mode in Tools > Options > Miscellaneous > Sonar Qube > Analysis Mode and set it to Preview.

Working for a real fix in the next version of the plugin.

Thanks.

**Comment by oers** [comment]
I tried to do this, but I can't Load the projetc list with:

![image](https://cloud.githubusercontent.com/assets/1115563/25340203/5067c462-2905-11e7-84c6-588a827e6a4c.png)

The combo box stays empty.

And in the SonarQube View I got the following Exception:

```
java.lang.ClassCastException: org.jdesktop.swingx.treetable.DefaultTreeTableModel cannot be cast to qubexplorer.ui.summary.SummaryModel
	at qubexplorer.ui.SonarIssuesTopComponent$6.itemStateChanged(SonarIssuesTopComponent.java:202)
	at javax.swing.AbstractButton.fireItemStateChanged(AbstractButton.java:2050)
	at javax.swing.AbstractButton$Handler.itemStateChanged(AbstractButton.java:2355)
	at javax.swing.DefaultButtonModel.fireItemStateChanged(DefaultButtonModel.java:455)
	at javax.swing.JToggleButton$ToggleButtonModel.setSelected(JToggleButton.java:272)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:289)
	at javax.swing.plaf.basic.BasicButtonListener.focusLost(BasicButtonListener.java:198)
	at java.awt.Component.processFocusEvent(Component.java:6425)
	at java.awt.Component.processEvent(Component.java:6289)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at ```

**Comment by hmvictor** [comment]
The option to change the analysis mode is here:

![image](https://cloud.githubusercontent.com/assets/11511471/25369656/1d1e1ad4-294b-11e7-9bc8-3e6fa46178d2.png)

Please, notify me if you still have problems after changing this setting in order to fix it.

Thanks for your feedback.

**Comment by oers** [comment]
I applied the settings, and still I can't get any reports:
with SonarQube -> Get Issues with Sonar Runner I get the following exception:
```
java.lang.NullPointerException
	at qubexplorer.server.SonarQube.getVersion(SonarQube.java:78)
	at qubexplorer.runner.SonarRunnerProccess.configureProperties(SonarRunnerProccess.java:116)
	at qubexplorer.runner.SonarRunnerProccess.createRunnerForProject(SonarRunnerProccess.java:103)
	at qubexplorer.runner.SonarRunnerProccess.executeRunner(SonarRunnerProccess.java:205)
	at qubexplorer.ui.summary.SonarRunnerTask.execute(SonarRunnerTask.java:102)
	at qubexplorer.ui.summary.SonarRunnerTask.execute(SonarRunnerTask.java:37)
	at qubexplorer.ui.task.TaskExecutor$TaskWorker.doInBackground(TaskExecutor.java:71)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[catch] at java.lang.Thread.run(Thread.java:745)
```
With the other options I get the SonarQube Server Connection Dialog which does not work:
 - List Issues is grey
- Load project list... does not work
 - with a wrong username/password I get: Please verify your user or password
 - with correct credentials nothing happens and I see the following exception in the IDE LOG:

```
INFO [qubexplorer.ui.task.TaskExecutor$TaskWorker]: qubexplorer.NoSuchProjectException
qubexplorer.NoSuchProjectException
	at qubexplorer.server.SonarQube.getSummary(SonarQube.java:307)
	at qubexplorer.ui.summary.SummaryTask.execute(SummaryTask.java:43)
	at qubexplorer.ui.summary.SummaryTask.execute(SummaryTask.java:24)
	at qubexplorer.ui.task.TaskExecutor$TaskWorker.doInBackground(TaskExecutor.java:71)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The project (and many others) are present in SonarQube.

So it seems, that the server can be reached but somethign else is wrong.

**Comment by oers** [comment]
With 3.0 I now get the following exception:
In the dialog I just point the server to the http base like:
http://sonar.corp/

The same URL works in the browser.
```
javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:199)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:170)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:482)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.get(ClientInvocationBuilder.java:175)
	at qubexplorer.server.SonarQube.getProjects(SonarQube.java:184)
	at qubexplorer.server.ui.ServerConnectionDialog$Projects2Task.execute(ServerConnectionDialog.java:368)
	at qubexplorer.server.ui.ServerConnectionDialog$Projects2Task.execute(ServerConnectionDialog.java:351)
	at qubexplorer.ui.task.TaskExecutor$TaskWorker.doInBackground(TaskExecutor.java:71)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[catch] at java.lang.Thread.run(Thread.java:745)
```

**Comment by hmvictor** [comment]
There was a change in the SonarQube API in version 6.3.

The fix is available in
https://github.com/hmvictor/radar-netbeans/tree/Radar-3.0.1 and the plugin
will be updated soon.

Greetings.

2017-06-14 2:23 GMT-05:00 oers <notifications@github.com>:
