### ISSUE TITLE
NPE in FileOpenedNotifier with SonarRunner (SonarQube 5.6.6)

### ISSUE THREAD

**Issue by daHaimi** [hmvictor/radar-netbeans#60]
Hi there,

I am using radar-netbeans 3.0.1 in NB 8.2 On Win7 with SonarQube 5.6.6.

Fetching from the server works fine, but when I try to execute SonarRunner un my local project, It takes about 5 Minutes, then the attached Exceptions occur.

My Project is a Gradle project with subprojects, but is also reproducable with plan NB projects.

I hope you can point the problem out for me.

Primary Exception:
`
java.lang.NullPointerException
	at qubexplorer.ui.FileOpenedNotifier.getFileObject(FileOpenedNotifier.java:84)
	at qubexplorer.ui.FileOpenedNotifier.propertyChange(FileOpenedNotifier.java:68)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at org.netbeans.core.windows.RegistryImpl.doFirePropertyChange(RegistryImpl.java:329)
	at org.netbeans.core.windows.RegistryImpl.access$100(RegistryImpl.java:69)
	at org.netbeans.core.windows.RegistryImpl$1.run(RegistryImpl.java:170)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

Secondary Exception (occurs twice)
`
java.util.MissingResourceException: Can't find resource for bundle org.openide.util.NbBundle$PBundle, key SonarRunner.error
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at org.openide.util.NbBundle.getMessage(NbBundle.java:642)
	at qubexplorer.runner.ui.SonarRunnerTask.fail(SonarRunnerTask.java:137)
	at qubexplorer.ui.task.TaskExecutor$TaskWorker.done(TaskExecutor.java:107)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

--
daHaimi

**Comment by hmvictor** [comment]
Hi, @daHaimi

The second exception is for some incorrect path and I'm fixing it. The first one, I'm still analyzing the possible cause.

**Comment by morpheus9999** [comment]
Hi, @hmvictor 
Any news?

**Comment by hmvictor** [comment]
I'm sorry for the delay @daHaimi  @morpheus9999 but it has been a hard time here in Mexico City. But I'm trying keeping up to date.

The missing key in the bundle was added and some missing verification was done to prevent a null value. This was not a expected return value from the Netbeans API but now I'm considering it. 

The error was happening when the annotations (error indicator) are attached in the source editor. So if the issue still happens, you can try to disable the editor annotations for verification.

![image](https://user-images.githubusercontent.com/11511471/31531135-b88f0f38-afaa-11e7-88c8-9c0e2e50a304.png)

The fix is in the 3.1 branch, so if you could make some test and give feedback would be very nice.

Thank you :)

**Comment by kandamuinc-git** [comment]
Hi there, I'm getting the same error. If you managed to resolve this, please share the details. 
Error: Can't find resource for bundle.org.openide.util.NbBundle$PBundle, key SonarRunner.error

**Comment by hmvictor** [comment]
Hi @muthu-k  , the fixed version is not the plugin center, but meanwhile, you can grab it here from the sources and make a build. It's easy and quick to run the build. 

Thanks.

**Comment by miguelcr1982** [comment]
Hello @hmvictor,

What a good project you have and it is working well for me with netbeans 12.2
[pom.txt](https://github.com/hmvictor/radar-netbeans/files/5838301/pom.txt)

Greetings and thanks!
