### ISSUE TITLE
Version 3.1 not compatible with Netbeans 9

### ISSUE THREAD

**Issue by Pell17** [hmvictor/radar-netbeans#68]
Getting issues from the server causes the following exception in Netbeans 9 (Java 10) on Windows 7.
Probably because of the new module concept, Jigsaw.

```
java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlElement
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:197)
Caused: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlElement starting from ModuleCL@6a75e023[org.radar.radar.netbeans] with possible defining loaders [ModuleCL@3c3769fb[org.netbeans.modules.xml.jaxb.api]] and declared parents [ModuleCL@6775b9b4[org.openide.dialogs], ModuleCL@562826b7[org.netbeans.libs.javacapi], ModuleCL@18b37b41[org.netbeans.api.progress], ModuleCL@1257655[org.openide.loaders], ModuleCL@4727180e[org.openide.awt], ModuleCL@1b01a037[org.openide.windows], ModuleCL@3098ccfc[org.netbeans.modules.settings], org.netbeans.MainImpl$BootClassLoader@2aac2a51, ModuleCL@2b4161da[org.netbeans.modules.projectapi], ModuleCL@56af6bb9[org.netbeans.api.annotations.common], ...10 more]
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:199)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
Caused: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlElement
	at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.<init>(JaxbAnnotationIntrospector.java:139)
	at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.<init>(JaxbAnnotationIntrospector.java:126)
	at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.<init>(JaxbAnnotationIntrospector.java:118)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.lang.Class.newInstance(Class.java:560)
	at com.fasterxml.jackson.jaxrs.json.JsonMapperConfigurator._resolveIntrospector(JsonMapperConfigurator.java:111)
	at com.fasterxml.jackson.jaxrs.json.JsonMapperConfigurator._resolveIntrospectors(JsonMapperConfigurator.java:84)
	at com.fasterxml.jackson.jaxrs.cfg.MapperConfiguratorBase._setAnnotations(MapperConfiguratorBase.java:120)
	at com.fasterxml.jackson.jaxrs.json.JsonMapperConfigurator.getDefaultMapper(JsonMapperConfigurator.java:45)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.locateMapper(ProviderBase.java:932)
	at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.readFrom(ResteasyJackson2Provider.java:113)
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:66)
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:56)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:248)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readEntity(ClientResponse.java:178)
	at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:212)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:101)
Caused: javax.ws.rs.client.ResponseProcessingException
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:137)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:473)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.get(ClientInvocationBuilder.java:169)
	at qubexplorer.server.SonarQube.getServerStatus(SonarQube.java:75)
	at qubexplorer.server.SonarQube.getVersion(SonarQube.java:70)
	at qubexplorer.server.SonarQube.getProjectsKeys(SonarQube.java:162)
	at qubexplorer.server.SonarQube.existsProject(SonarQube.java:228)
	at qubexplorer.server.SonarQube.getSummary(SonarQube.java:238)
	at qubexplorer.ui.summary.SummaryTask.execute(SummaryTask.java:45)
	at qubexplorer.ui.summary.SummaryTask.execute(SummaryTask.java:25)
	at qubexplorer.ui.task.TaskExecutor$TaskWorker.doInBackground(TaskExecutor.java:71)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[catch] at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by Pell17** [comment]
The workaround described in https://stackoverflow.com/a/43574427/6044979 works, i.e. in netbeans.conf add to `netbeans_default_options`:
`-J--add-modules=jdk.jshell,java.xml.bind`

(`jdk.jshell` is already present)

**Comment by hmvictor** [comment]
Hi, @Pell17 

Many thanks for your tip to make it work. I will add support for Netbeans 9 soon.

Regards.

**Comment by hmvictor** [comment]
Hi @Pell17.

I'm creating a new branch 3.2 to make fixes for Netbeans 9 support and Java 9 too.

I already added the fix that is mentioned in the StackOverFlow link to use the xml apis.

So many thanks.

**Comment by luiscla27** [comment]
@hmvictor is there any release of branch 3.2?

Also, there would be a release for Java 11?? thats specially important because the `--add-modules=java.xml.bind` solution doesn't work on it.

**Comment by hmvictor** [comment]
Hi, @luiscla27 

I was expecting some stabilization for Netbeans and now that NB 11 version was released I can release that latest branch too.
