### ISSUE TITLE
Get Issues From Server 

### ISSUE THREAD

**Issue by fascalsj** [hmvictor/radar-netbeans#69]
I have select Get Issues from server but failed, i used Mac OS Mojave, Java 8
Help me Please, Error Message is :

java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at org.apache.http.impl.io.AbstractSessionOutputBuffer.flushBuffer(AbstractSessionOutputBuffer.java:159)
	at org.apache.http.impl.io.AbstractSessionOutputBuffer.flush(AbstractSessionOutputBuffer.java:166)
	at org.apache.http.impl.AbstractHttpClientConnection.doFlush(AbstractHttpClientConnection.java:272)
	at org.apache.http.impl.AbstractHttpClientConnection.flush(AbstractHttpClientConnection.java:277)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.flush(ManagedClientConnectionImpl.java:190)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:240)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:122)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:686)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:488)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:286)
Caused: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:290)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:435)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:471)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.get(ClientInvocationBuilder.java:169)
	at qubexplorer.server.SonarQube.getServerStatus(SonarQube.java:75)
	at qubexplorer.server.SonarQube.getVersion(SonarQube.java:70)
	at qubexplorer.server.SonarQube.getProjectsKeys(SonarQube.java:162)
	at qubexplorer.server.SonarQube.existsProject(SonarQube.java:228)
	at qubexplorer.server.SonarQube.getSummary(SonarQube.java:238)
	at qubexplorer.ui.summary.SummaryTask.execute(SummaryTask.java:45)
	at qubexplorer.ui.summary.SummaryTask.execute(SummaryTask.java:25)
	at qubexplorer.ui.task.TaskExecutor$TaskWorker.doInBackground(TaskExecutor.java:70)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[catch] at java.lang.Thread.run(Thread.java:745)

**Comment by hmvictor** [comment]
Hi,  @fascalsj .

What version of SonarQube and Netbeans are you using?

**Comment by fascalsj** [comment]
I use Netbean 8.2

**Comment by hmvictor** [comment]
And SonarQube server version?

**Comment by fascalsj** [comment]
The last sonar in repo git

**Comment by sharpedavid** [comment]
I'm getting a similar error:

> java.net.ConnectException: Connection refused: connect
> 	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
> 	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> 	at java.net.Socket.connect(Socket.java:589)
> 	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:120)
> 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
> 	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:328)
> 	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
> 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
> 	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
> 	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:286)
> Caused: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
> 	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:290)
> 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:435)
> 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:471)
> 	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.get(ClientInvocationBuilder.java:169)
> 	at qubexplorer.server.SonarQube.getServerStatus(SonarQube.java:75)
> 	at qubexplorer.server.SonarQube.getVersion(SonarQube.java:70)
> 	at qubexplorer.runner.SonarRunnerProccess.configureProperties(SonarRunnerProccess.java:135)
> 	at qubexplorer.runner.SonarRunnerProccess.createRunnerForProject(SonarRunnerProccess.java:122)
> 	at qubexplorer.runner.SonarRunnerProccess.executeRunner(SonarRunnerProccess.java:219)
> 	at qubexplorer.runner.ui.SonarRunnerTask.execute(SonarRunnerTask.java:99)
> 	at qubexplorer.runner.ui.SonarRunnerTask.execute(SonarRunnerTask.java:39)
> 	at qubexplorer.ui.task.TaskExecutor$TaskWorker.doInBackground(TaskExecutor.java:70)
> 	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at javax.swing.SwingWorker.run(SwingWorker.java:334)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [catch] at java.lang.Thread.run(Thread.java:748)

I use Netbean 8.2, Sonar Qube Version 6.7.1, Windows 10, Java 8, radar-netbeans 3.1.

**Comment by sharpedavid** [comment]
False alarm! I just needed to configure the server URL in Netbeans. I assumed it would read it from the "sonar-project.properties" property file.
