### ISSUE TITLE
The preview mode, along with the 'sonar.analysis.mode' parameter, is no more supported

### ISSUE THREAD

**Issue by luiscla27** [hmvictor/radar-netbeans#71]
When i try to run `sonar-runner` i get the following exception.

![image](https://user-images.githubusercontent.com/29953012/56775347-51fb0b00-678c-11e9-8113-ef29a148eca9.png)

This is my current setting:

- Apache NetBeans IDE 10.0 (Build incubator-netbeans-release-380-on-20181217) running on Java 10.0.2 64-Bit Server VM
- SonnarQuebe Community Edition Version 7.7 (build 23042)
- radar-netbeans release 3.1

```
Starting sonar-runner
INFO: SonarQube Server 7.7.0.23042
18:52:46.581 INFO  - Load global settings
18:52:47.753 INFO  - Load global settings (done) | time=1174ms
18:52:47.756 INFO  - Server id: AD158016-AVuIAJrorZdCHikbasno
18:52:47.767 INFO  - User cache: C:\Users\Bnext\.sonar\cache
18:52:47.770 INFO  - Load/download plugins
18:52:47.771 INFO  - Load plugins index
18:52:48.931 INFO  - Load plugins index (done) | time=1160ms
18:54:14.081 INFO  - Load/download plugins (done) | time=86311ms
Exception in thread "main" org.sonar.runner.impl.RunnerException: Unable to execute Sonar
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
	at org.sonar.runner.impl.BatchLauncherMain.execute(BatchLauncherMain.java:41)
	at org.sonar.runner.impl.BatchLauncherMain.main(BatchLauncherMain.java:59)
Caused by: The preview mode, along with the 'sonar.analysis.mode' parameter, is no more supported. You should stop using this parameter.
Error executing sonar-runner
```

**Comment by hmvictor** [comment]
Have you tried to change de analysis mode in the plugin options? 

Tools > Options > Miscellaneous > SonarQube

**Comment by seet61** [comment]
I have the same issue too. 
I changed the settings, but the error persists.
NetBeans 8.2
Radar-netbeans 3.1
SonarQube Community EditionVersion 7.7 (build 23042)

**Comment by luiscla27** [comment]
Yes @hmvictor, i've just tested both analisis mode `Preview` and `Incremental`, both throws the same error.

**Comment by hmvictor** [comment]
Hi, @luiscla27 

The problem is that SonarQube 7.7 has removed some parameters and APIs and the plugin needs those APIs to work. 

I recommend to use with the LTS version for now (SonarQube 6.7).

**Comment by luiscla27** [comment]
Thanks for your feedback @hmvictor
