### ISSUE TITLE
Version 3.2 does not work with Netbeans 11 running with JDK 8

### ISSUE THREAD

**Issue by lalo-mx** [hmvictor/radar-netbeans#75]
Running Netbeans 11 with JDK 8 does not show radar in the Project and the options Tabs is empty.

radar-netbeans: 3.2

[ide.log](https://github.com/hmvictor/radar-netbeans/files/3214288/ide.log)

```
ALL [null]: value = qubexplorer.ui.PopupAction from Actions/Build/qubexplorer-ui-SonarQube.instance
WARNING [org.openide.util.Utilities]: Unrecognized object of class java.lang.Object found in actions path Projects/org-netbeans-modules-maven/Actions
INFO [org.netbeans.core.startup.layers.BinaryFS]: value = qubexplorer.ui.SonarQubeOptionsPanelController from OptionsDialog/Advanced/qubexplorer-ui-SonarQubeOptionsPanelController.instance
java.lang.UnsupportedClassVersionError: qubexplorer/ui/SonarQubeOptionsPanelController has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at org.netbeans.JarClassLoader.doLoadClass(JarClassLoader.java:286)

```

**Comment by hmvictor** [comment]
What version of the plugin are you using?

**Comment by lalo-mx** [comment]
3,2 downloaded from http://plugins.netbeans.org/download/plugin/10044

**Comment by hmvictor** [comment]
The problem is that the main fix of 3.2 release is support for Java modules
(available from Java 9).

If you use an older JDK, I recommend to make a manual installation of 3.1
in Netbeans 11.

**Comment by lalo-mx** [comment]
Thanks for the response. In the Plugins Center there is not information about JDK compatibility. That would be a nice addition. I will try to use to older version but the last time i tested the plugin it was not working due to the SonarQube API changes.
